<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="0" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-26T20:34:50 IST" name="Suite" finished-at="2025-04-26T20:35:52 IST" duration-ms="62235">
    <groups>
    </groups>
    <test started-at="2025-04-26T20:34:50 IST" name="Test" finished-at="2025-04-26T20:35:52 IST" duration-ms="62235">
      <class name="QA.test.TestSample">
        <test-method is-config="true" signature="startReporter()[pri:0, instance:QA.test.TestSample@69453e37]" started-at="2025-04-26T20:34:50 IST" name="startReporter" finished-at="2025-04-26T20:34:52 IST" duration-ms="1382" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReporter -->
        <test-method is-config="true" signature="setUpBrowser(java.lang.String,java.lang.reflect.Method)[pri:0, instance:QA.test.TestSample@69453e37]" started-at="2025-04-26T20:34:52 IST" name="setUpBrowser" finished-at="2025-04-26T20:35:03 IST" duration-ms="11066" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void QA.test.TestSample.sampleMethodToForEnteringCred()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBrowser -->
        <test-method retried="true" signature="sampleMethodToForEnteringCred()[pri:0, instance:QA.test.TestSample@69453e37]" started-at="2025-04-26T20:35:03 IST" name="sampleMethodToForEnteringCred" finished-at="2025-04-26T20:35:12 IST" duration-ms="9096" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Cogmento CRM1] but found [Cogmento CRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Cogmento CRM1] but found [Cogmento CRM]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Pages.LoginPage.verifyLoginPageLoaded(LoginPage.java:16)
at QA.test.TestSample.sampleMethodToForEnteringCred(TestSample.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleMethodToForEnteringCred -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:QA.test.TestSample@69453e37]" started-at="2025-04-26T20:35:12 IST" name="afterMethod" finished-at="2025-04-26T20:35:13 IST" duration-ms="1019" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=sampleMethodToForEnteringCred status=SKIP method=TestSample.sampleMethodToForEnteringCred()[pri:0, instance:QA.test.TestSample@69453e37] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:QA.test.TestSample@69453e37]" started-at="2025-04-26T20:35:13 IST" name="afterTest" finished-at="2025-04-26T20:35:14 IST" duration-ms="766" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="setUpBrowser(java.lang.String,java.lang.reflect.Method)[pri:0, instance:QA.test.TestSample@69453e37]" started-at="2025-04-26T20:35:14 IST" name="setUpBrowser" finished-at="2025-04-26T20:35:16 IST" duration-ms="2756" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void QA.test.TestSample.sampleMethodToForEnteringCred()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBrowser -->
        <test-method retried="true" signature="sampleMethodToForEnteringCred()[pri:0, instance:QA.test.TestSample@69453e37]" started-at="2025-04-26T20:35:16 IST" name="sampleMethodToForEnteringCred" finished-at="2025-04-26T20:35:28 IST" duration-ms="12047" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Cogmento CRM1] but found [Cogmento CRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Cogmento CRM1] but found [Cogmento CRM]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Pages.LoginPage.verifyLoginPageLoaded(LoginPage.java:16)
at QA.test.TestSample.sampleMethodToForEnteringCred(TestSample.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleMethodToForEnteringCred -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:QA.test.TestSample@69453e37]" started-at="2025-04-26T20:35:28 IST" name="afterMethod" finished-at="2025-04-26T20:35:33 IST" duration-ms="4704" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=sampleMethodToForEnteringCred status=SKIP method=TestSample.sampleMethodToForEnteringCred()[pri:0, instance:QA.test.TestSample@69453e37] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:QA.test.TestSample@69453e37]" started-at="2025-04-26T20:35:33 IST" name="afterTest" finished-at="2025-04-26T20:35:33 IST" duration-ms="143" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="setUpBrowser(java.lang.String,java.lang.reflect.Method)[pri:0, instance:QA.test.TestSample@69453e37]" started-at="2025-04-26T20:35:33 IST" name="setUpBrowser" finished-at="2025-04-26T20:35:40 IST" duration-ms="6682" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void QA.test.TestSample.sampleMethodToForEnteringCred()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBrowser -->
        <test-method signature="sampleMethodToForEnteringCred()[pri:0, instance:QA.test.TestSample@69453e37]" started-at="2025-04-26T20:35:40 IST" name="sampleMethodToForEnteringCred" finished-at="2025-04-26T20:35:51 IST" duration-ms="11191" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Cogmento CRM1] but found [Cogmento CRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Cogmento CRM1] but found [Cogmento CRM]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Pages.LoginPage.verifyLoginPageLoaded(LoginPage.java:16)
at QA.test.TestSample.sampleMethodToForEnteringCred(TestSample.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleMethodToForEnteringCred -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:QA.test.TestSample@69453e37]" started-at="2025-04-26T20:35:52 IST" name="afterMethod" finished-at="2025-04-26T20:35:52 IST" duration-ms="866" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=sampleMethodToForEnteringCred status=FAILURE method=TestSample.sampleMethodToForEnteringCred()[pri:0, instance:QA.test.TestSample@69453e37] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:QA.test.TestSample@69453e37]" started-at="2025-04-26T20:35:52 IST" name="afterTest" finished-at="2025-04-26T20:35:52 IST" duration-ms="55" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- QA.test.TestSample -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
